import { Component } from '@angular/core';
@Component({
  selector: 'demo-progress-bar', template: `<div class="component-demo"><div class="demo-header"><h1>Progress Bar</h1><p>Barra di progresso per indicare lo stato di avanzamento.</p></div><div class="demo-tabs"><div class="tab-nav"><button class="tab-btn" [class.active]="activeTab==='preview'" (click)="activeTab='preview'">Preview</button><button class="tab-btn" [class.active]="activeTab==='code'" (click)="activeTab='code'">Code</button><button class="tab-btn" [class.active]="activeTab==='api'" (click)="activeTab='api'">API</button></div><div class="tab-content" *ngIf="activeTab==='preview'"><div class="demo-section" style="display:flex;flex-direction:column;gap:24px"><h3>Progress Bar</h3><div class="preview-area"><p style="margin-bottom:8px;font-weight:500">25% completato</p><ngx-sirio-progress-bar [value]="25" label="Caricamento"></ngx-sirio-progress-bar></div><div class="preview-area"><p style="margin-bottom:8px;font-weight:500">50% completato</p><ngx-sirio-progress-bar [value]="50" label="Download"></ngx-sirio-progress-bar></div><div class="preview-area"><p style="margin-bottom:8px;font-weight:500">75% completato</p><ngx-sirio-progress-bar [value]="75" label="Installazione"></ngx-sirio-progress-bar></div><div class="preview-area"><p style="margin-bottom:8px;font-weight:500">100% completato</p><ngx-sirio-progress-bar [value]="100" label="Completato"></ngx-sirio-progress-bar></div></div></div><div class="tab-content" *ngIf="activeTab==='code'"><div class="demo-section"><div class="code-block"><div class="code-header"><span class="code-lang">HTML</span></div><pre>{{ code }}</pre></div></div></div><div class="tab-content" *ngIf="activeTab==='api'"><h3>Inputs</h3><table class="api-table"><thead><tr><th>Nome</th><th>Tipo</th><th>Descrizione</th></tr></thead><tbody><tr><td><code>value</code></td><td><code>number</code></td><td>Valore (0-100)</td></tr><tr><td><code>label</code></td><td><code>string</code></td><td>Label</td></tr></tbody></table></div></div></div>`,
  styles: [`:host{display:block} .demo-header{margin-bottom:24px} .demo-header h1{font-size:2rem} .demo-header p{color:#5a6270} :host ::ng-deep ngx-sirio-progress-bar .progress{height:16px!important} :host ::ng-deep ngx-sirio-progress-bar .progress-bar{height:16px!important}`]
})
export class ProgressBarDemoComponent {
  activeTab = 'preview';
  code = `<ngx-sirio-progress-bar [value]="25" label="Caricamento"></ngx-sirio-progress-bar>
<ngx-sirio-progress-bar [value]="50" label="Download"></ngx-sirio-progress-bar>
<ngx-sirio-progress-bar [value]="75" label="Installazione"></ngx-sirio-progress-bar>
<ngx-sirio-progress-bar [value]="100" label="Completato"></ngx-sirio-progress-bar>`;
}
