import { Component } from '@angular/core';
@Component({
    selector: 'demo-searchbar', template: `<div class="component-demo"><div class="demo-header"><h1>Searchbar</h1><p>Barra di ricerca con icona e clear button.</p></div><div class="demo-tabs"><div class="tab-nav"><button class="tab-btn" [class.active]="activeTab==='preview'" (click)="activeTab='preview'">Preview</button><button class="tab-btn" [class.active]="activeTab==='code'" (click)="activeTab='code'">Code</button><button class="tab-btn" [class.active]="activeTab==='api'" (click)="activeTab='api'">API</button></div><div class="tab-content" *ngIf="activeTab==='preview'"><div class="demo-section"><h3>Searchbar Default</h3><div class="preview-area"><ngx-sirio-searchbar label="Cerca" placeholder="Cerca..."></ngx-sirio-searchbar></div></div><div class="demo-section"><h3>Searchbar con buttonLabel personalizzato</h3><div class="preview-area"><ngx-sirio-searchbar label="Cerca" placeholder="Cerca..." buttonLabel="Trova"></ngx-sirio-searchbar></div></div></div><div class="tab-content" *ngIf="activeTab==='code'"><div class="demo-section"><div class="code-block"><div class="code-header"><span class="code-lang">HTML - Default</span></div><pre>{{ codeDefault }}</pre></div></div><div class="demo-section"><div class="code-block"><div class="code-header"><span class="code-lang">HTML - Button Label personalizzato</span></div><pre>{{ codeCustomButton }}</pre></div></div></div><div class="tab-content" *ngIf="activeTab==='api'"><h3>Inputs</h3><table class="api-table"><thead><tr><th>Nome</th><th>Tipo</th><th>Descrizione</th></tr></thead><tbody><tr><td><code>label</code></td><td><code>string</code></td><td>Label del campo di ricerca</td></tr><tr><td><code>placeholder</code></td><td><code>string</code></td><td>Placeholder dell'input</td></tr><tr><td><code>buttonLabel</code></td><td><code>string</code></td><td>Testo del pulsante di ricerca (default: "Ricerca")</td></tr><tr><td><code>clearLabel</code></td><td><code>string</code></td><td>Label del pulsante di pulizia</td></tr><tr><td><code>searchAriaLabel</code></td><td><code>string</code></td><td>Aria label per il pulsante di ricerca</td></tr><tr><td><code>name</code></td><td><code>string</code></td><td>Nome del campo</td></tr><tr><td><code>items</code></td><td><code>string[]</code></td><td>Elementi per l'autocomplete</td></tr></tbody></table><h3>Outputs</h3><table class="api-table"><thead><tr><th>Nome</th><th>Tipo</th><th>Descrizione</th></tr></thead><tbody><tr><td><code>onSearch</code></td><td><code>EventEmitter</code></td><td>Emesso quando si clicca il pulsante di ricerca</td></tr><tr><td><code>onClear</code></td><td><code>EventEmitter</code></td><td>Emesso quando si clicca il pulsante di pulizia</td></tr></tbody></table></div></div></div>`,
    styles: [`:host{display:block} .demo-header{margin-bottom:24px} .demo-header h1{font-size:2rem} .demo-header p{color:#5a6270} .api-table{width:100%;border-collapse:collapse;margin-top:16px} .api-table th,.api-table td{text-align:left;padding:12px;border-bottom:1px solid #e2e8f0} .api-table th{font-weight:600;color:#1a202c}`]
})
export class SearchbarDemoComponent {
    activeTab = 'preview';
    codeDefault = `<ngx-sirio-searchbar label="Cerca" placeholder="Cerca..."></ngx-sirio-searchbar>`;
    codeCustomButton = `<ngx-sirio-searchbar label="Cerca" placeholder="Cerca..." buttonLabel="Trova"></ngx-sirio-searchbar>`;
}
