import { Component } from '@angular/core';
@Component({
    selector: 'demo-tooltip', template: `<div class="component-demo"><div class="demo-header"><h1>Tooltip</h1><p>Tooltip su hover o focus con posizionamento personalizzabile.</p></div><div class="demo-tabs"><div class="tab-nav"><button class="tab-btn" [class.active]="activeTab==='preview'" (click)="activeTab='preview'">Preview</button><button class="tab-btn" [class.active]="activeTab==='code'" (click)="activeTab='code'">Code</button><button class="tab-btn" [class.active]="activeTab==='api'" (click)="activeTab='api'">API</button></div><div class="tab-content" *ngIf="activeTab==='preview'"><div class="demo-section"><h3>Tooltip</h3><div class="preview-area"><span sirioTooltip="Questo è un tooltip" style="padding:8px 16px;background:#e8ecf0;border-radius:4px;cursor:pointer;">Hover su di me</span></div></div></div><div class="tab-content" *ngIf="activeTab==='code'"><div class="demo-section"><div class="code-block"><div class="code-header"><span class="code-lang">HTML</span></div><pre>{{ code }}</pre></div></div></div><div class="tab-content" *ngIf="activeTab==='api'"><h3>Directive</h3><table class="api-table"><thead><tr><th>Selettore</th><th>Tipo</th><th>Descrizione</th></tr></thead><tbody><tr><td><code>[sirioTooltip]</code></td><td><code>string</code></td><td>Testo del tooltip</td></tr></tbody></table></div></div></div>`,
    styles: [`:host{display:block} .demo-header{margin-bottom:24px} .demo-header h1{font-size:2rem} .demo-header p{color:#5a6270} .api-table{width:100%;border-collapse:collapse;margin-top:16px} .api-table th,.api-table td{text-align:left;padding:12px;border-bottom:1px solid #e2e8f0} .api-table th{font-weight:600;color:#1a202c}`]
})
export class TooltipDemoComponent {
    activeTab = 'preview';
    code = `<span sirioTooltip="Questo è un tooltip">Hover su di me</span>`;
}
