import { Component } from '@angular/core';
@Component({
  selector: 'demo-footer', template: `<div class="component-demo"><div class="demo-header"><h1>Footer</h1><p>Piè di pagina dell'applicazione. Componente complesso che richiede configurazione tramite servizi.</p></div><div class="demo-tabs"><div class="tab-nav"><button class="tab-btn" [class.active]="activeTab==='preview'" (click)="activeTab='preview'">Preview</button><button class="tab-btn" [class.active]="activeTab==='code'" (click)="activeTab='code'">Code</button><button class="tab-btn" [class.active]="activeTab==='api'" (click)="activeTab='api'">API</button></div><div class="tab-content" *ngIf="activeTab==='preview'"><div class="demo-section"><h3>Footer demo</h3><div class="preview-area" style="background:#1a1a2e;padding:24px;border-radius:8px;color:#e0e0e0"><div style="display:flex;gap:48px;margin-bottom:16px;flex-wrap:wrap"><div><h4 style="color:#fff;margin:0 0 8px 0;font-size:0.95rem">Servizi</h4><ul style="list-style:none;padding:0;margin:0;font-size:0.85rem;line-height:1.8"><li><a href="#" style="color:#aab;text-decoration:none">Prestazioni</a></li><li><a href="#" style="color:#aab;text-decoration:none">Contributi</a></li><li><a href="#" style="color:#aab;text-decoration:none">Assistenza</a></li></ul></div><div><h4 style="color:#fff;margin:0 0 8px 0;font-size:0.95rem">Contatti</h4><ul style="list-style:none;padding:0;margin:0;font-size:0.85rem;line-height:1.8"><li style="color:#aab">📧 info&#64;esempio.it</li><li style="color:#aab">📞 +39 06 1234567</li></ul></div><div><h4 style="color:#fff;margin:0 0 8px 0;font-size:0.95rem">Social</h4><ul style="list-style:none;padding:0;margin:0;font-size:0.85rem;line-height:1.8"><li><a href="#" style="color:#aab;text-decoration:none">Twitter</a></li><li><a href="#" style="color:#aab;text-decoration:none">LinkedIn</a></li></ul></div></div><div style="border-top:1px solid #333;padding-top:12px;font-size:0.8rem;color:#777">© 2024 - Tutti i diritti riservati</div></div><p style="margin-top:12px;color:#5a6270;font-size:0.85rem"><em>Nota: Il componente <code>ngx-sirio-footer</code> richiede la configurazione tramite il servizio <code>StructureService</code>. Sopra una preview statica dell'aspetto.</em></p></div></div><div class="tab-content" *ngIf="activeTab==='code'"><div class="demo-section"><div class="code-block"><div class="code-header"><span class="code-lang">HTML</span></div><pre>{{ code }}</pre></div></div></div><div class="tab-content" *ngIf="activeTab==='api'"><h3>Note</h3><p>Il componente <code>ngx-sirio-footer</code> non ha input diretti. Viene configurato tramite il <code>StructureService</code>.</p></div></div></div>`,
  styles: [`:host{display:block} .demo-header{margin-bottom:24px} .demo-header h1{font-size:2rem} .demo-header p{color:#5a6270}`]
})
export class FooterDemoComponent {
  activeTab = 'preview';
  code = `<!-- Il footer richiede la configurazione del StructureService -->
<ngx-sirio-footer></ngx-sirio-footer>

<!-- Nel modulo: provideHost('assets/structure.json') -->`;
}
