import { Component } from '@angular/core';
@Component({
  selector: 'demo-header', template: `<div class="component-demo"><div class="demo-header"><h1>Header</h1><p>Barra di navigazione principale dell'applicazione. Componente complesso che richiede configurazione tramite servizi.</p></div><div class="demo-tabs"><div class="tab-nav"><button class="tab-btn" [class.active]="activeTab==='preview'" (click)="activeTab='preview'">Preview</button><button class="tab-btn" [class.active]="activeTab==='code'" (click)="activeTab='code'">Code</button><button class="tab-btn" [class.active]="activeTab==='api'" (click)="activeTab='api'">API</button></div><div class="tab-content" *ngIf="activeTab==='preview'"><div class="demo-section"><h3>Header demo</h3><div class="preview-area" style="background:#0066cc;padding:16px 24px;border-radius:8px;color:#fff;display:flex;align-items:center;gap:24px"><div style="font-weight:700;font-size:1.25rem">📌 Logo Sito</div><nav style="display:flex;gap:16px"><a href="#" style="color:#fff;text-decoration:none;opacity:0.9">Home</a><a href="#" style="color:#fff;text-decoration:none;opacity:0.9">Servizi</a><a href="#" style="color:#fff;text-decoration:none;opacity:0.9">Contatti</a></nav><div style="margin-left:auto;opacity:0.8;font-size:0.85rem">🔍 Cerca</div></div><p style="margin-top:12px;color:#5a6270;font-size:0.85rem"><em>Nota: Il componente <code>ngx-sirio-header</code> richiede la configurazione tramite il servizio <code>StructureService</code> con dati JSON. Sopra una preview statica dell'aspetto.</em></p></div></div><div class="tab-content" *ngIf="activeTab==='code'"><div class="demo-section"><div class="code-block"><div class="code-header"><span class="code-lang">HTML</span></div><pre>{{ code }}</pre></div></div></div><div class="tab-content" *ngIf="activeTab==='api'"><h3>Note</h3><p>Il componente <code>ngx-sirio-header</code> non ha input diretti. Richiede la configurazione del <code>StructureService</code> con un file JSON di struttura che definisce logo, menu, e navigazione.</p><table class="api-table"><thead><tr><th>Servizio</th><th>Descrizione</th></tr></thead><tbody><tr><td><code>StructureService</code></td><td>Gestisce i dati strutturali per header e footer</td></tr></tbody></table></div></div></div>`,
  styles: [`:host{display:block} .demo-header{margin-bottom:24px} .demo-header h1{font-size:2rem} .demo-header p{color:#5a6270}`]
})
export class HeaderDemoComponent {
  activeTab = 'preview';
  code = `<!-- L'header richiede la configurazione del StructureService -->
<ngx-sirio-header></ngx-sirio-header>

<!-- Nel modulo: provideHost('assets/structure.json') -->`;
}
